version: "3.8"

services:
  mongodb:
    image : mongo
    container_name: mongodb
    # environment:
      # - MONGO_INITDB_ROOT_USERNAME=mongoadmin
      # - MONGO_INITDB_ROOT_PASSWORD=mongoadmin
    volumes:
      - ./db:/data/db
    ports:
      - 27017:27017
      - 27018:27018

    restart: unless-stopped