export MONGO_URL=mongodb://localhost:27017
export MONGO_RequestTimeOut=10
export NATS_URL=localhost:4222
export NATS_NKEY=
export NATS_NOTIFICATION_PREFIX=NOTIFICATION
export NATS_NOTIFICATION_REPLICAS=1
export NATS_NOTIFICATION_RETRY_DURATIONS=30,60,100,600,1200
export NATS_NOTIFICATION_RETRY_UNIT=Second

